### PR TITLE
Feature/open mfdataset

### LINKED ISSUE #126: ENH: use open_mfdataset when reading netcdf files
It would be nice if the input forcings to metsim (`forcing` config option) was allowed to be a glob-like file path. This, combined with xarray.open_mfdataset() will allow for the input of multiple forcing files, munged together via xarray.

### PR DESCRIPTION
**Pull request by jhamman**
- [x] closes #126
 - [x] tests passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

### CODE REVIEW

**Comment by arbennett** [comment]
Can you give an example of how this would work in a configuration file, or is this mainly for scripting purposes?

**Comment by jhamman** [comment]
What I'd like to be able to do in the configuration file is either:

```yaml
forcing = "/path/to/forcing/files/forcings_by_year*nc"
```

Where the wildcard is expanded to a selection of files. Or provide a list of inputs files that xarray can concatenate/merge:

```yaml
forcing =  ["/path/to/forcing/files/forcings_by_year_2000.nc", "/path/to/forcing/files/forcings_by_year_2001.nc"]
```

**Comment by arbennett** [comment]
Thanks, I think supporting both is a good idea.

**Comment by jhamman** [comment]
The changes in this PR enable both, while at the same time still supporting a single file as an input.

**Pull request merged**
